export const posts = [
  {
    id: 1,
    title: "Next.js and the shift",
    description:
      "A post on how Next.js makes it easy to integrate frontend and backend code",
    body: "Next.js has revolutionized the way developers build full-stack applications. By seamlessly integrating frontend and backend code in a single framework, it eliminates the complexity of managing separate projects.",
    likes: 20,
    comments: 100,
  },
  {
    id: 2,
    title: "React Hooks Guide",
    description: "Understanding React Hooks and how to use them effectively",
    body: "React Hooks allow you to use state and other React features without writing class components. This guide covers useState, useEffect, useContext, and custom hooks to help you write cleaner, more reusable code.",
    likes: 35,
    comments: 85,
  },
  {
    id: 3,
    title: "CSS Grid Layout",
    description: "A comprehensive guide to CSS Grid for modern web layouts",
    body: "CSS Grid is a powerful layout system that allows you to create complex, responsive designs with minimal code. Learn about grid containers, items, and how to create flexible layouts that work on all devices.",
    likes: 28,
    comments: 62,
  },
  {
    id: 4,
    title: "JavaScript Async/Await",
    description: "Master asynchronous programming with async and await",
    body: "Async/await syntax makes asynchronous code look and behave more like synchronous code. This guide shows you how to handle promises elegantly, manage errors with try/catch, and write more readable async functions.",
    likes: 42,
    comments: 110,
  },
  {
    id: 5,
    title: "TypeScript Basics",
    description: "Getting started with TypeScript for type-safe JavaScript",
    body: "TypeScript adds static typing to JavaScript, catching errors at compile time. Learn about basic types, interfaces, generics, and how TypeScript can improve your code quality and development experience.",
    likes: 31,
    comments: 75,
  },
  {
    id: 6,
    title: "API Design Best Practices",
    description: "Learn how to design clean and maintainable REST APIs",
    body: "Good API design is crucial for building scalable applications. This article covers RESTful principles, proper HTTP methods, versioning strategies, error handling, and documentation best practices.",
    likes: 45,
    comments: 95,
  },
  {
    id: 7,
    title: "Database Optimization",
    description: "Tips and tricks for optimizing database performance",
    body: "Database performance can make or break your application. Explore indexing strategies, query optimization, caching techniques, and monitoring tools to keep your database running efficiently.",
    likes: 22,
    comments: 55,
  },
  {
    id: 8,
    title: "Web Performance Metrics",
    description: "Understanding Core Web Vitals and improving site speed",
    body: "Core Web Vitals measure user experience across loading, interactivity, and visual stability. Learn how to measure LCP, FID, and CLS, and implement strategies to improve these critical metrics.",
    likes: 38,
    comments: 78,
  },
  {
    id: 9,
    title: "Mobile-First Design",
    description: "Building responsive websites with mobile-first approach",
    body: "Mobile-first design means starting with mobile layouts and progressively enhancing for larger screens. This approach ensures better performance and usability across all devices.",
    likes: 26,
    comments: 68,
  },
  {
    id: 10,
    title: "Git Workflow Essentials",
    description: "Master version control with Git best practices",
    body: "Git is essential for modern development. Learn about branching strategies, commit messages, merging, rebasing, and collaboration workflows to streamline your team's development process.",
    likes: 19,
    comments: 42,
  },
  {
    id: 11,
    title: "Docker Containerization",
    description: "Simplify deployment with Docker containers",
    body: "Docker containers package your application and its dependencies, ensuring consistency across development and production environments. Master Dockerfiles, images, and container orchestration.",
    likes: 40,
    comments: 88,
  },
  {
    id: 12,
    title: "GraphQL Fundamentals",
    description: "Query language and runtime for modern APIs",
    body: "GraphQL provides a flexible alternative to REST APIs. Learn about queries, mutations, subscriptions, and how to build powerful APIs that clients can query exactly what they need.",
    likes: 33,
    comments: 72,
  },
  {
    id: 13,
    title: "State Management Patterns",
    description: "Choosing the right state management solution",
    body: "Managing state is complex in large applications. Explore Redux, Zustand, Context API, and other patterns to find the best solution for your project's needs.",
    likes: 27,
    comments: 61,
  },
  {
    id: 14,
    title: "Testing Best Practices",
    description: "Writing effective unit and integration tests",
    body: "Testing ensures code reliability and maintainability. Learn about unit tests, integration tests, mocking, and testing frameworks to build a robust test suite.",
    likes: 41,
    comments: 92,
  },
  {
    id: 15,
    title: "Security in Web Apps",
    description: "Essential security practices for modern web applications",
    body: "Security is paramount in web development. Protect against CSRF, XSS, SQL injection, and other attacks by implementing proper authentication, validation, and security headers.",
    likes: 48,
    comments: 105,
  },
  {
    id: 16,
    title: "Authentication Methods",
    description: "Implementing OAuth, JWT, and session-based auth",
    body: "Choose the right authentication method for your application. Compare OAuth, JWT tokens, and session-based approaches, and learn implementation best practices for each.",
    likes: 36,
    comments: 81,
  },
  {
    id: 17,
    title: "Microservices Architecture",
    description: "Building scalable systems with microservices",
    body: "Microservices break monolithic applications into smaller, independent services. Learn about service discovery, communication patterns, and managing distributed systems.",
    likes: 30,
    comments: 70,
  },
  {
    id: 18,
    title: "Cloud Deployment Guide",
    description: "Deploy applications to AWS, Azure, or GCP",
    body: "Cloud platforms offer scalable infrastructure for your applications. Explore deployment options on AWS, Azure, and GCP, including serverless, containers, and virtual machines.",
    likes: 25,
    comments: 59,
  },
  {
    id: 19,
    title: "Monitoring and Logging",
    description: "Implement effective monitoring and log aggregation",
    body: "Monitoring and logging are crucial for production applications. Set up alerts, aggregate logs, track metrics, and troubleshoot issues with proper observability practices.",
    likes: 23,
    comments: 51,
  },
  {
    id: 20,
    title: "Developer Tools and Extensions",
    description: "Essential tools to boost your productivity",
    body: "Discover essential developer tools and VS Code extensions that can enhance your productivity, improve code quality, and streamline your development workflow.",
    likes: 32,
    comments: 74,
  },
];
